AWSTemplateFormatVersion: '2010-09-09'
Description: CloudMediaConverter and Storage on AWS

Resources:
  PlaceholderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloud-media-converter-placeholder
